### ISSUE TITLE
Logging out causes problems

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#286]
Logging out and back in can lead to connection issues.
Using the app with multiple users can cause problems.

Maybe the cookies aren't cleared on logout?

**Comment by baka-kaba** [comment]
I think I've fixed this, the cookie gets cleared but the activity doesn't realise it needs to be rebuilt, because the check and rebuild happens in onCreate. So even after you log in it's sending empty cookies all over the place

I haven't tried anything with multiple users, what are the problems?

**Comment by Sereri** [comment]
I don't fully remember but I think the app just wasn't able to make connections anymore. Might've been at least partially fixed a while ago.

**Comment by Sereri** [comment]
Avatar in the sidebar stays when another user logs in. Not sure if account settings (platinum etc) get resetted, though it should.
